provider = 'deepseek'

[providers.dashscope]
api_key = 'sk-***'
base_url = 'https://dashscope.aliyuncs.com/api/v2/apps/protocols/compatible-mode/v1'

[providers.dashscope.model]
primary = 'qwen3.5-397b-a17b'
light = 'qwen3.6-35b-a3b'

[providers.deepseek]
api_key = 'sk-***'
base_url = 'https://api.deepseek.com'

[providers.deepseek.model]
primary = 'deepseek-v4-pro'
light = 'deepseek-v4-flash'
